#include<stdio.h>
#include<conio.h>
#include<dos.h>
#include<string.h>
void dit()
{
	sound(1000);
	printf(". ");
	delay(200);
	nosound();
	delay(200);
}
void dah()
{
	sound(2000);
	printf("_ ");
	delay(600);
	nosound();
	delay(200);
}
void main()
{
	char string[200],ch;
	int i,len,j;
	clrscr();
	printf("Enter string\n");
	gets(string);
	len=0;
	strupr(string);
	while(ch!='\0')
	{
		ch=string[len];
		switch(ch)
		{
			case 'A':dit();
				 dah();
				 break;
			case 'B':dah();
				 dit();
				 dit();
				 dit();
				 break;
			case 'C':dah();
				 dit();
				 dah();
				 dit();
				 break;
			case 'D':dah();
				 dit();
				 dit();
				 break;
			case 'E':dit();
				 break;
			case 'F':dit();
				 dit();
				 dah();
				 dit();
				 break;
			case 'G':dah();
				 dah();
				 dit();
				 break;
			case 'H':dit();
				 dit();
				 dit();
				 dit();
				 break;
			case 'I':dit();
				 dit();
				 break;
			case 'J':dit();
				 dah();
				 dah();
				 dah();
				 break;
			case 'K':dah();
				 dit();
				 dah();
				 break;
			case 'L':dit();
				 dah();
				 dit();
				 dit();
				 break;
			case 'M':dah();
				 dah();
				 break;
			case 'N':dah();
				 dit();
				 break;
			case 'O':dah();
				 dah();
				 dah();
				 break;
			case 'P':dit();
				 dah();
				 dah();
				 dit();
				 break;
			case 'Q':dah();
				 dah();
				 dit();
				 dah();
				 break;
			case 'R':dit();
				 dah();
				 dit();
				 break;
			case 'S':dit();
				 dit();
				 dit();
				 break;
			case 'T':dah();
				 break;
			case 'U':dit();
				 dit();
				 dah();
				 break;
			case 'V':dit();
				 dit();
				 dit();
				 dah();
				 break;
			case 'W':dit();
				 dah();
				 dah();
				 break;
			case 'X':dah();
				 dit();
				 dit();
				 dah();
				 break;
			case 'Y':dah();
				 dit();
				 dah();
				 dah();
				 break;
			case 'Z':dah();
				 dah();
				 dit();
				 dit();
				 break;
			case '1':dit();
				 dah();
				 dah();
				 dah();
				 dah();
				 break;
			case '2':dit();
				 dit();
				 dah();
				 dah();
				 dah();
				 break;
			case '3':dit();
				 dit();
				 dit();
				 dah();
				 dah();
				 break;
			case '4':dit();
				 dit();
				 dit();
				 dit();
				 dah();
				 break;
			case '5':dit();
				 dit();
				 dit();
				 dit();
				 dit();
				 break;
			case '6':dah();
				 dit();
				 dit();
				 dit();
				 dit();
				 break;
			case '7':dah();
				 dah();
				 dit();
				 dit();
				 dit();
				 break;
			case '8':dah();
				 dah();
				 dah();
				 dit();
				 dit();
				 break;
			case '9':dah();
				 dah();
				 dah();
				 dah();
				 dit();
				 break;
			case '0':dah();
				 dah();
				 dah();
				 dah();
				 dah();
				 break;
			case ' ':printf("       ");
				 delay(200);
				 break;
			default:printf("\nEnd of transmission\n");
		}
		printf("   ");
		len=len+1;
	}
	getch();
}